name = "fc-caesar-salad"
compatibility_date = "2026-08-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "fc-caesar-salad-db"
database_id = "0832d6dc-c1f9-4ada-9609-099a19b29974"
